### ISSUE TITLE
no implicit conversion of Integer into String

### ISSUE THREAD

**Issue by yegor256** [yegor256/iri#6]
```
no implicit conversion of Integer into String
	/app/vendor/bundle/ruby/2.6.0/gems/iri-0.4.0/lib/iri.rb:171:in `escape'
	/app/vendor/bundle/ruby/2.6.0/gems/iri-0.4.0/lib/iri.rb:171:in `block in append'
	/app/vendor/bundle/ruby/2.6.0/gems/iri-0.4.0/lib/iri.rb:179:in `modify'
	/app/vendor/bundle/ruby/2.6.0/gems/iri-0.4.0/lib/iri.rb:170:in `append'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.1`
